// The release tools decide a version that can never be taken back, the crates an SBOM claims
// and what a changelog tells a reader to download, so each rule they apply is pinned here.
//
//   node --test tools/release/
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import { answered } from "./github.mjs";
import { createRef, refState } from "./github-ref.mjs";
import { lockSubset, parseCrates } from "./lock-subset.mjs";
import { previousRelease, pullRequestNumber, renderNotes, shipsInDownload } from "./notes.mjs";
import { bump, compareVersions, inspect, nextVersion, workspaceVersion } from "./version.mjs";

const MANIFEST = `[workspace]
resolver = "3"
members = ["crates/one", "crates/two"]

[workspace.package]
version = "0.3.9"
edition = "2024"

[workspace.dependencies]
one = { path = "crates/one", version = "1.0.0" }
`;

const LOCK = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "one"
version = "0.3.9"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aa"

[[package]]
name = "serde"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb"

[[package]]
name = "two"
version = "0.3.9"
`;

function workspace({ manifest = MANIFEST, lock = LOCK, two = "version.workspace = true" } = {}) {
  const root = mkdtempSync(join(tmpdir(), "release-test-"));
  writeFileSync(join(root, "Cargo.toml"), manifest);
  writeFileSync(join(root, "Cargo.lock"), lock);
  for (const [name, version] of [
    ["one", "version.workspace = true"],
    ["two", two],
  ]) {
    mkdirSync(join(root, "crates", name), { recursive: true });
    writeFileSync(join(root, "crates", name, "Cargo.toml"), `[package]\nname = "${name}"\n${version}\n\n[dependencies]\nx = { version = "9.9.9" }\n`);
  }
  return root;
}

test("versions order as semver orders them", () => {
  assert.ok(compareVersions("0.10.0", "0.9.9") > 0);
  assert.ok(compareVersions("1.0.0-rc.1", "1.0.0") < 0);
  assert.ok(compareVersions("1.0.0-rc.2", "1.0.0-rc.10") < 0);
  assert.ok(compareVersions("1.0.0-alpha", "1.0.0-alpha.1") < 0);
  assert.equal(compareVersions("2.1.3", "2.1.3"), 0);
});

test("a bump only ever moves forward", () => {
  assert.equal(nextVersion("0.3.9", "patch"), "0.3.10");
  assert.equal(nextVersion("0.3.9", "minor"), "0.4.0");
  assert.equal(nextVersion("0.3.9", "major"), "1.0.0");
  assert.equal(nextVersion("0.3.9", "1.0.0-rc.1"), "1.0.0-rc.1");
  assert.throws(() => nextVersion("0.3.9", "0.3.9"), /does not come after/);
  assert.throws(() => nextVersion("0.3.9", "0.2.0"), /does not come after/);
  assert.throws(() => nextVersion("1.0.0-rc.1", "patch"), /pre-release/);
  assert.throws(() => nextVersion("0.3.9", "v0.4.0"), /Not a version/);
});

test("the workspace version is read from its own table, not a dependency's", () => {
  assert.equal(workspaceVersion(MANIFEST), "0.3.9");
  assert.equal(workspaceVersion("[package]\nversion = \"1.0.0\"\n"), null);
});

test("a bump moves the manifest and exactly the workspace's lock entries", () => {
  const root = workspace();
  try {
    const result = bump(root, "minor");
    assert.deepEqual(result, { from: "0.3.9", to: "0.4.0", files: ["Cargo.toml", "Cargo.lock"] });
    const manifest = readFileSync(join(root, "Cargo.toml"), "utf8");
    assert.match(manifest, /\[workspace\.package\]\nversion = "0\.4\.0"/);
    assert.match(manifest, /version = "1\.0\.0" \}/);
    const lock = readFileSync(join(root, "Cargo.lock"), "utf8");
    assert.equal(lock, LOCK.replaceAll('version = "0.3.9"', 'version = "0.4.0"'));
    assert.deepEqual(inspect(root).problems, []);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("a crate with its own version is refused", () => {
  const root = workspace({ two: 'version = "0.3.9"' });
  try {
    assert.match(inspect(root).problems.join("\n"), /two sets its own version/);
    assert.throws(() => bump(root, "patch"), /two sets its own version/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("a lock file behind the manifest is refused", () => {
  const root = workspace({ lock: LOCK.replace('name = "two"\nversion = "0.3.9"', 'name = "two"\nversion = "0.3.8"') });
  try {
    assert.deepEqual(inspect(root).problems, ["Cargo.lock records two 0.3.8, not 0.3.9."]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("the lock subset keeps exactly the crates named, and the header", () => {
  const { text, kept, of } = lockSubset(LOCK, parseCrates("one 0.3.9\nserde 2.0.0\n"));
  assert.equal(kept, 2);
  assert.equal(of, 4);
  assert.ok(text.startsWith("# This file is automatically @generated by Cargo."));
  assert.match(text, /name = "serde"\nversion = "2\.0\.0"/);
  assert.doesNotMatch(text, /version = "1\.0\.0"/);
  assert.doesNotMatch(text, /name = "two"/);
});

test("a crate the lock does not hold is an error, not an omission", () => {
  assert.throws(() => lockSubset(LOCK, parseCrates("serde 3.0.0")), /does not hold: serde 3\.0\.0/);
  assert.throws(() => parseCrates("serde v1.0.0 (proc-macro)"), /Not a "name version" line/);
});

test("the changelog splits on what reaches the download", () => {
  assert.equal(shipsInDownload(["crates/steamgauge-core/src/read.rs"]), true);
  assert.equal(shipsInDownload(["Cargo.lock"]), true);
  assert.equal(shipsInDownload(["rust-toolchain.toml"]), true);
  assert.equal(shipsInDownload([".github/workflows/release-build.yml"]), true);
  assert.equal(shipsInDownload(["training/train.py", "crates/steamgauge-core/src/taxonomy.rs"]), true);
  assert.equal(shipsInDownload(["crates/steamgauge-core/examples/sample-report.rs"]), false);
  assert.equal(shipsInDownload(["crates/steamgauge-core/tests/pipeline.rs"]), false);
  assert.equal(shipsInDownload(["training/train.py", "reference/README.md", "tools/chrome.mjs"]), false);
  assert.equal(shipsInDownload(["DECISIONS.md", ".github/workflows/ci.yml", "training/Cargo.lock"]), false);
});

test("pull requests are found by the number a squash appends", () => {
  assert.equal(pullRequestNumber("An encoder is traced as it is (#135)"), 135);
  assert.equal(pullRequestNumber("Mentions #12 in passing"), null);
});

test("the previous release is the newest below the tag, even once the tag is released", () => {
  const tags = ["v0.2.0", "v0.10.0", "v0.9.1", "v1.0.0-rc.1", "nightly"];
  assert.equal(previousRelease(tags, "1.0.0"), "v1.0.0-rc.1");
  assert.equal(previousRelease(tags, "0.10.0"), "v0.9.1");
  assert.equal(previousRelease(tags, "0.2.0"), null);
});

test("the notes list each side under its own heading and link the range", () => {
  const notes = renderNotes(
    [
      { title: "Reads faster", author: "a", url: "u1", ships: true },
      { title: "A training run", author: "b", url: "u2", ships: false },
    ],
    "o/r",
    "v0.1.0",
    "v0.2.0",
  );
  assert.equal(
    notes,
    [
      "## What's Changed",
      "",
      "### In what you download",
      "",
      "* Reads faster by @a in u1",
      "",
      "### Repository only: training, reference data, tools, CI and docs",
      "",
      "* A training run by @b in u2",
      "",
      "**Full Changelog**: https://github.com/o/r/compare/v0.1.0...v0.2.0",
      "",
    ].join("\n"),
  );
  assert.match(renderNotes([], "o/r", null, "v0.1.0"), /commits\/v0\.1\.0/);
});

const still = async () => {};

test("a server error is asked again, and a 404 is an answer", async () => {
  const answers = [{ status: 503, body: "" }, { status: 404, body: {} }];
  const seen = [];
  const ask = async (method, path) => {
    seen.push(`${method} ${path}`);
    return answers.shift();
  };
  assert.equal(await refState(ask, "o/r", "tags/v1.0.0", still), "absent");
  assert.equal(seen.length, 2);
  await assert.rejects(
    answered(async () => ({ status: 502, body: "down" }), still, "Reading"),
    /failed on all 5 attempts/,
  );
});

test("creating a ref that exists at the same commit is success, at another is refused", async () => {
  const at = (sha) => async (method) =>
    method === "POST" ? { status: 422, body: {} } : { status: 200, body: { object: { sha } } };
  assert.equal(await createRef(at("abc"), "o/r", "tags/v1.0.0", "abc", still), "existed");
  await assert.rejects(createRef(at("def"), "o/r", "tags/v1.0.0", "abc", still), /already exists at def/);
});
